### PR TITLE
Adding a ping all unaccepted feature.

### PR DESCRIPTION
**Pull request by Acoliver102**
This a pretty heavy-handed attempt to add a command that pings all unaccepted players in the last queue that popped. I have a variable in queueMessageService that tracks the UUID of the most recent match, and from there can call all the missing players from that request.

I then call that function in the Queue commands under a new ping command.

It probably would have some issues scaling to multiple queues running simultaneously (e.g. one normal and one comp at the same time) but other than that I think it would work.

Not exactly elegant, but it gets the job done (hopefully). I haven't been able to test this though, so if someone could that would be great. Been having issues with my setup.

### CODE REVIEW

**Comment by AMTitan** [comment]
Because the pings are in the embed it wont work. I will list the players but it wont actually ping them. You will need to put it in the actually content for the ping to go through.

**Comment by AMTitan** [comment]
Also I believe you need to clear the `lastMatchId` because if a game is running and it was the last game it would say 
```
Missing players: 
```
but no missing players after it. While it should say there is no game.

**Comment by Acoliver102** [comment]
On the empty missing players issue, I check if the MatchID is in the list of current matches. Since the match will get removed from that list when it is finished, there is no need to reset the MatchID.

It would be easy enough to make it null on handling the end of a queue, so I can do that if this is an issue.

**Comment by AMTitan** [comment]
> On the empty missing players issue, I check if the MatchID is in the list of current matches. Since the match will get removed from that list when it is finished, there is no need to reset the MatchID.

It does get removed but if the game is currently on then it will do the issue I was talking about.

**Comment by AMTitan** [comment]
I also dont know if this is the "correct" way to code this, but you can use this function I made at https://github.com/BigBoot/fang/pull/16/files#diff-29775e4174150a2ffa1f23f055a4b7e46c982f590881c73e1c077bee2f2a10afR400-R407. You could find the author of the message then find what pop they are in. That way you dont need to store the last game uuid.

**Pull request closed without merging**
